### PR TITLE
ref(redmine): update to 3.2.1 and switch to bitnami redmine image

### PR DESCRIPTION
**Pull request by prydonius**
We would like to take over the maintenance of the Redmine chart, using the [Bitnami Docker Image for Redmine](https://github.com/bitnami/bitnami-docker-redmine).

This chart depends on the MariaDB chart (#82), and therefore is more suitable for production deployments due to separation of data. It also makes use of generators for configuring the database credentials, Redmine admin credentials and SMTP settings.

This update is not backwards compatible with the current chart, and will require users to migrate their existing data in order to upgrade.

### CODE REVIEW

**Comment by bacongobbler** [comment]
hey @prydonius!

Are there certain limitations to the official redmine image? As far as I know it shouldn't be hard to add a `mysql` replication controller/service combo, then add the following to the chart to communicate with an external database:

```
env:
  - name: MYSQL_PORT_3306_TCP
    value: $(MYSQL_SERVICE_PORT)
```

That can be implemented as an enhancement to the chart. The original redmine chart is just a bare example that we created when first implementing Helm, though please feel free to enhance it as you see fit.

With that said, would it be possible to introduce this as a separate chart like `redmine-bitnami`, or even add this to your own personal chart repository? I'd personally prefer using the "official" Docker images where possible as the default, unless there's a specific reason against using them. Extending the redmine image is do-able, we just haven't gotten around to doing that yet.

I'm always open to others' suggestions, so if the bitnami image is preferred over the official image then I'd be okay with this.

**Comment by prydonius** [comment]
Hey @bacongobbler, sorry for the delay in responding; I'm globe-trotting this week.

Although you're right that the official Redmine image can be configured to talk to an external database, we have built our Redmine image with a focus on suitability for use in production. For example, our Redmine image exposes SMTP configuration as environment variables which is pretty important for non-lab use, and is something the official Redmine image is lacking. 

As you may know, in Bitnami when a new security issue comes about we push out security updates within hours of a fix, and having control over our own Docker images allows us to keep up with that release cadence. This is why we think this will be a more fully-featured chart than an enhanced version of the existing chart.

When talking to @gabrtv about contributing charts, it sounded like complete, production ready and up-to-date charts would be really valuable to the Helm project. We're hoping to contribute a lot more applications and components geared for production use, so we're really grateful for any feedback on Redmine and MariaDB. If you have any more guidance on what would be desirable that would be really helpful :).

**Comment by krancour** [comment]
Looks like this PR hasn't received any attention in a while. Just following up...

> With that said, would it be possible to introduce this as a separate chart like redmine-bitnami, or even add this to your own personal chart repository?

I might agree with @bacongobbler here. Is the source for the Bitnami images (i.e. the Dockerfile and all other resources) open source? I think we should be careful to not include anything closed-source in the helm/charts repo, but we like that Bitnami is embracing Helm and I think it would be awesome if there were a bitnami/charts repo that was chalk full of useful, production-quality charts, regardless of whether those are open source or not.

**Comment by prydonius** [comment]
Hey @krancour,

We've so far been maintaining our charts repo over at https://github.com/bitnami/charts which has been great, and is something we will continue to do.

To address some of your concerns, all the Bitnami images are publicly available in their respective GitHub repos (Redmine lives in https://github.com/bitnami/bitnami-docker-redmine). The Dockerfile pulls in some packages using the `bitnami-pkg` tool. These packages make use of the Nami tool (https://github.com/bitnami/nami) previously codenamed harpoon, which is open source. The packages are not currently published on GitHub, but you can see that the `bitnami-pkg` is pulling them from our downloads server/S3 bucket (https://github.com/bitnami/stacksmith-base/blob/master/rootfs/usr/local/bin/bitnami-pkg#L108).

**Comment by sgoings** [comment]
@prydonius now that you're involved in the core kubernetes/helm project... do you want to focus your efforts over there and close this out knowing that helm-classic will eventually be sunsetted?

**Comment by prydonius** [comment]
@sgoings agreed, I was actually going to suggest closing this out now that we're focusing our efforts on Kubernetes/Helm 👍

**Pull request closed without merging**
