### PR TITLE
feat(postgresql): add postgres chart

### PR DESCRIPTION
**Pull request by bacongobbler**

### CODE REVIEW

**Comment by technosophos** [comment]
Could we rename this to `postgres-standalone`? Maybe we should opt toward that as a convention when we have just single instances of a service (as opposed to clusters).

**Comment by bacongobbler** [comment]
From my interpretation of https://github.com/deis/charts/pull/1#issuecomment-151304079, I was under the impression that `n` and `n-cluster` should be the naming convention. If that's the direction we want to go, shall I create a new PR to rename the existing projects and add a document to "formalize" it (at least the conventions)?

**Comment by technosophos** [comment]
@bacongobbler OK. That makes sense to me.

**Comment by technosophos** [comment]
Although I just checked, and it looks like we might be labeling both standalone and cluster like that: https://github.com/deis/charts/pull/2

**Comment by bacongobbler** [comment]
All right. All my PRs have been renamed to `n-standalone` or `n-cluster`. I can revert this change if it looks ugly (tbh it does to me) but they're all ready to go.

**Pull request merged**
