### PR TITLE
feat(charts): etcd-cluster

### PR DESCRIPTION
**Pull request by remohammadi**
The idea of 3 pods comes from [this example](https://github.com/coreos/etcd/tree/master/hack/kubernetes-deploy).
The pods are replaced by `ReplicationController`s.

### CODE REVIEW

**Comment by remohammadi** [comment]
It seems not so stable on our cluster after just one day. I'm closing this PR to debug it more thoroughly.

**Comment by sgoings** [comment]
Thanks for putting it through its paces and testing it thoroughly, @remohammadi! :smile:

**Comment by technosophos** [comment]
@remohammadi I don't know if you've seen https://github.com/deis/etcd, but that might give you a few ideas on setting up an etcd cluster inside k8s. We decided to add an in-cluster discovery service to get around some of the stability issues.

**Comment by remohammadi** [comment]
@technosophos Thank you. It's working for us. We used the deis etcd to manage [vulcand](https://github.com/vulcand/vulcand) load balancer for our cluster. So the written chart for vulcand is dependent on `deis-etcd-1`.

So, which of these options do you recommend?
1. Creating a pull request for vulcand, commenting the dependency, noting the deis etcd in Readme, and waiting for the time the deis etcd is in stable phase.
2. Creating a pull request for the current status of deis-etcd (with _heavy development_ warning in its Readme) + another pull request for vulcand

Or any other suggestions?

**Comment by technosophos** [comment]
Here's a crazy idea on decoupling that you might find interesting, @remohammadi: In your Vulcand chart, add a service called something like `vuldcand-etcd`, and make it a clone of the `deis-etcd` service (so it uses the same label selector and all). Then you can swap different etcd implementations in and out without having to hard-code `deis-etcd-1` into your own code (code in `vulcan-etcd` instead). Then you can set up defaults to, say, the Deis etcd or to a stand-alone etcd instance, or whatever.

Based on all of that, I _think_ option 1 is the right approach. FWIW, we're about to mark the etcd alpha1 release, at which point all we'll be working on from here is stability, recovery, and fault tolerance.

**Pull request closed without merging**
